//
//  Theme.swift
//  test_yoga_ios
//
//  Created by Chang Liu on 2/9/26.
//

import SwiftUI

// MARK: - Theme Colors
// Color.yogaPrimary, Color.yogaSecondary, Color.yogaSurface, Color.yogaCardBackground
// are auto-generated by Xcode from Assets.xcassets colorsets.

// MARK: - Theme Shadows

extension View {
    func yogaCardShadow() -> some View {
        self
            .shadow(color: .black.opacity(0.08), radius: 8, x: 0, y: 4)
            .shadow(color: .black.opacity(0.04), radius: 2, x: 0, y: 1)
    }

    func yogaFloatingShadow() -> some View {
        self
            .shadow(color: .black.opacity(0.12), radius: 12, x: 0, y: 6)
            .shadow(color: .black.opacity(0.06), radius: 4, x: 0, y: 2)
    }

    func yogaScreenBackground() -> some View {
        self.background(Color.yogaSurface)
    }
}

// MARK: - Theme Fonts

extension Font {
    static func yogaTitle(_ size: CGFloat = 28) -> Font {
        .system(size: size, weight: .bold, design: .rounded)
    }

    static func yogaHeadline(_ size: CGFloat = 17) -> Font {
        .system(size: size, weight: .semibold, design: .rounded)
    }
}
